version: '3'

services:
    postgres:
        image: postgres
        container_name: finance-app-postgres
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
            POSTGRES_DB: finance-app
        ports:
            - '5432:5432'
        volumes:
            - ./.postgres-data:/var/lib/postgresql/data
